[build]
builder = "DOCKERFILE"
dockerfilePath = "api/Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "api"
type = "web"
plan = "free"

[services.env]
PORT = "8000"